UPDATE JOB_DEFINITION
SET ACTIVE = 1 
WHERE JOB_NAME = 'PaymentCaptureJob';

INSERT INTO JOB_STEP (JOB_STEP_ID, JOB_ID, ACTIVE, PRIORITY, CLASS_NAME, EMAIL_NOTIFICATION, JOB_NOTIFICATION_ID)
VALUES ((SELECT MAX_ID + 1 FROM MAX_ID WHERE TABLE_NAME='JOB_STEP'), (SELECT J.JOB_ID FROM JOB_DEFINITION J WHERE J.JOB_NAME = 'PaymentCaptureJob'), 1, 1, 'paymentCaptureJobStep', 'nomail@marketlive.com', 1);

UPDATE MAX_ID
SET MAX_ID = MAX_ID + 1
WHERE TABLE_NAME='JOB_STEP';

UPDATE JOB_DEFINITION
SET ACTIVE = 1 
WHERE JOB_NAME = 'PaymentRefundJob';

INSERT INTO JOB_STEP (JOB_STEP_ID, JOB_ID, ACTIVE, PRIORITY, CLASS_NAME, EMAIL_NOTIFICATION, JOB_NOTIFICATION_ID)
VALUES ((SELECT MAX_ID + 1 FROM MAX_ID WHERE TABLE_NAME='JOB_STEP'), (SELECT J.JOB_ID FROM JOB_DEFINITION J WHERE J.JOB_NAME = 'PaymentRefundJob'), 1, 1, 'paymentRefundJobStep', 'nomail@marketlive.com', 1);

COMMIT;