INSERT INTO JOB_DEFINITION (JOB_ID, JOB_NAME, JOB_GROUP, CLASS_NAME, EMAIL_NOTIFICATION, ACTIVE, START_TIME, END_TIME, 
							REPEAT_COUNT, REPEAT_INTERVAL_DAYS, REPEAT_INTERVAL_HOURS, REPEAT_INTERVAL_MIN, 
							REPEAT_INTERVAL_SEC, DATE_MODIFIED, DELETE_FLAG, DATE_DELETED, JOB_NOTIFICATION_ID, DATE_OVERRIDE)
VALUES ((SELECT MAX_ID + 1 FROM MAX_ID WHERE TABLE_NAME='JOB_DEFINITION'), 'PaymentVoidJob', 'Payments', 'com.marketlive.scheduler.controller.MLJobController', 'mljobscheduler@marketlive.com', 1, 4511823120000, 0, -1, 1, 0, 0, 0, 1457887680000, 0, 0, 1, 0);

UPDATE MAX_ID
SET MAX_ID = MAX_ID + 1
WHERE TABLE_NAME='JOB_DEFINITION';

INSERT INTO JOB_STEP (JOB_STEP_ID, JOB_ID, ACTIVE, PRIORITY, CLASS_NAME, EMAIL_NOTIFICATION, JOB_NOTIFICATION_ID)
VALUES ((SELECT MAX_ID + 1 FROM MAX_ID WHERE TABLE_NAME='JOB_STEP'), (SELECT J.JOB_ID FROM JOB_DEFINITION J WHERE J.JOB_NAME = 'PaymentVoidJob'), 1, 1, 'paymentVoidJobStep', 'nomail@marketlive.com', 1);

UPDATE MAX_ID
SET MAX_ID = MAX_ID + 1
WHERE TABLE_NAME='JOB_STEP';

COMMIT;